version: "3"

networks:
    xarxa_gp1f4a11:
        driver: bridge

services:
    ipcalc:
        build: .
        expose:
            - "8080"
        volumes:
             - ./app:/var/www/html
        networks:
             - xarxa_gp1f4a11
    lb:
        image: nginx:latest
        volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        - ipcalc
        ports:
        - "8000:80"
        networks:
            - xarxa_gp1f4a11
